const fs = require('fs');

const definitions = {
  "Array": "A data structure consisting of a collection of elements, each identified by at least one array index or key.",
  "Linked List": "A linear collection of data elements whose order is not given by their physical placement in memory, but by pointers.",
  "Stack": "An abstract data type that serves as a collection of elements, with two main operations: push (add) and pop (remove), following LIFO.",
  "Queue": "A collection of entities that are maintained in a sequence and can be modified by the addition of entities at one end and the removal from the other end (FIFO).",
  "Tree": "A widely used abstract data type that simulates a hierarchical tree structure, with a root value and subtrees of children with a parent node.",
  "Graph": "A structure amounting to a set of objects in which some pairs of the objects are in some sense 'related' via edges.",
  "Hash Table": "A data structure that implements an associative array abstract data type, a structure that can map keys to values.",
  "Heap": "A specialized tree-based data structure which is essentially an almost complete tree that satisfies the heap property.",
  "Trie": "A type of search tree, a tree data structure used for locating specific keys from within a set.",
  "B-Tree": "A self-balancing tree data structure that maintains sorted data and allows searches, sequential access, insertions, and deletions in logarithmic time.",
  
  "Binary Search": "A search algorithm that finds the position of a target value within a sorted array.",
  "Merge Sort": "An efficient, general-purpose, and comparison-based sorting algorithm based on the divide and conquer strategy.",
  "Quick Sort": "An efficient, general-purpose sorting algorithm. It works by selecting a 'pivot' element and partitioning the array.",
  "Bubble Sort": "A simple sorting algorithm that repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order.",
  "Dijkstra": "An algorithm for finding the shortest paths between nodes in a graph.",
  "DFS": "Depth-first search is an algorithm for traversing or searching tree or graph data structures.",
  "BFS": "Breadth-first search is an algorithm for searching a tree data structure for a node that satisfies a given property.",
  "Dynamic Programming": "A method for solving a complex problem by breaking it down into a collection of simpler subproblems.",
  "Greedy": "An algorithmic paradigm that follows the problem-solving heuristic of making the locally optimal choice at each stage.",
  "Backtracking": "A general algorithm for finding all solutions to some computational problems, notably constraint satisfaction problems.",
  
  "HTML": "HyperText Markup Language is the standard markup language for documents designed to be displayed in a web browser.",
  "CSS": "Cascading Style Sheets is a style sheet language used for describing the presentation of a document written in HTML.",
  "JavaScript": "A programming language that is one of the core technologies of the World Wide Web, used for creating interactive effects.",
  "React": "A free and open-source front-end JavaScript library for building user interfaces based on components.",
  "DOM": "The Document Object Model is a cross-platform and language-independent interface that treats an XML or HTML document as a tree structure.",
  "REST API": "An application programming interface that conforms to the constraints of REST architectural style.",
  "GraphQL": "An open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data.",
  "JWT": "JSON Web Token is an open standard that defines a compact and self-contained way for securely transmitting information.",
  "CORS": "Cross-Origin Resource Sharing is a mechanism that allows restricted resources on a web page to be requested from another domain.",
  "WebSockets": "A computer communications protocol, providing full-duplex communication channels over a single TCP connection.",

  "SQL": "Structured Query Language is a domain-specific language used in programming and designed for managing data held in an RDBMS.",
  "NoSQL": "A non-relational database that provides a mechanism for storage and retrieval of data that is modeled in means other than tabular relations.",
  "Normalization": "The process of structuring a relational database in accordance with a series of normal forms in order to reduce data redundancy.",
  "ACID": "Atomicity, Consistency, Isolation, Durability - a set of properties of database transactions intended to guarantee validity.",
  "Index": "A data structure that improves the speed of data retrieval operations on a database table.",
  "Foreign Key": "A set of attributes in a table that refers to the primary key of another table.",
  "Primary Key": "A specific choice of a minimal set of attributes that uniquely specify a tuple in a relation.",
  "Join": "An SQL operation that combines columns from one or more tables in a relational database.",
  "Transaction": "A unit of work performed within a database management system against a database.",
  "Sharding": "A type of database partitioning that separates very large databases the into smaller, faster, more easily managed parts.",

  "TCP": "Transmission Control Protocol is one of the main protocols of the Internet protocol suite.",
  "UDP": "User Datagram Protocol is one of the core members of the Internet protocol suite. It provides connectionless datagram services.",
  "HTTP": "Hypertext Transfer Protocol is an application layer protocol in the Internet protocol suite model for distributed, collaborative, hypermedia information systems.",
  "HTTPS": "Hypertext Transfer Protocol Secure is an extension of the Hypertext Transfer Protocol. It is used for secure communication.",
  "DNS": "The Domain Name System is a hierarchical and decentralized naming system for computers, services, or other resources.",
  "IP Address": "A numerical label assigned to each device connected to a computer network that uses the Internet Protocol.",
  "MAC Address": "A media access control address is a unique identifier assigned to a network interface controller.",
  "Router": "A networking device that forwards data packets between computer networks.",
  "Switch": "A networking hardware that connects devices on a computer network by using packet switching to receive and forward data.",
  "Firewall": "A network security system that monitors and controls incoming and outgoing network traffic.",

  "Process": "An instance of a computer program that is being executed by one or many threads.",
  "Thread": "The smallest sequence of programmed instructions that can be managed independently by a scheduler.",
  "Deadlock": "A state in which each member of a group is waiting for another member, including itself, to take action.",
  "Mutex": "A mutual exclusion object that allows multiple program threads to share the same resource, such as file access, but not simultaneously.",
  "Semaphore": "A variable or abstract data type used to control access to a common resource by multiple processes.",
  "Virtual Memory": "A memory management technique that provides an idealized abstraction of the storage resources that are actually available on a given machine.",
  "Paging": "A memory management scheme by which a computer stores and retrieves data from secondary storage for use in main memory.",
  "Scheduling": "The method by which work is assigned to resources that complete the work.",
  "Kernel": "The core of a computer's operating system, with complete control over everything in the system.",
  "Shell": "A user interface for access to an operating system's services.",

  "Phishing": "The fraudulent attempt to obtain sensitive information by disguising oneself as a trustworthy entity.",
  "Malware": "Any software intentionally designed to cause damage to a computer, server, client, or computer network.",
  "Encryption": "The process of encoding information.",
  "Decryption": "The process of decoding data that has been encrypted into a secret format.",
  "Symmetric Key": "Algorithms for cryptography that use the same cryptographic keys for both encryption of plaintext and decryption of ciphertext.",
  "Asymmetric Key": "Public-key cryptography, a cryptographic system that uses pairs of keys.",
  "Hash Function": "Any function that can be used to map data of arbitrary size to fixed-size values.",
  "Salting": "Random data that is used as an additional input to a one-way function that hashes data, a password or passphrase.",
  "VPN": "A virtual private network extends a private network across a public network.",
  "DDoS": "A distributed denial-of-service attack is a malicious attempt to disrupt normal traffic by overwhelming the target.",

  "IaaS": "Infrastructure as a Service provides virtualized computing resources over the internet.",
  "PaaS": "Platform as a Service provides a platform allowing customers to develop, run, and manage applications.",
  "SaaS": "Software as a Service is a software licensing and delivery model in which software is centrally hosted.",
  "AWS": "Amazon Web Services is a subsidiary of Amazon providing on-demand cloud computing platforms.",
  "Azure": "Microsoft Azure is a cloud computing service operated by Microsoft.",
  "Docker": "A set of platform as a service products that use OS-level virtualization to deliver software in packages called containers.",
  "Kubernetes": "An open-source container-orchestration system for automating computer application deployment, scaling, and management.",
  "Serverless": "A cloud computing execution model in which the cloud provider dynamically manages the allocation and provisioning of servers.",
  "Microservices": "An architectural style that structures an application as a collection of services that are highly maintainable and testable.",
  "Load Balancer": "A device that acts as a reverse proxy and distributes network or application traffic across a number of servers.",

  "Supervised Learning": "The machine learning task of learning a function that maps an input to an output based on example input-output pairs.",
  "Unsupervised Learning": "A type of machine learning that looks for previously undetected patterns in a data set with no pre-existing labels.",
  "Neural Network": "A series of algorithms that endeavors to recognize underlying relationships in a set of data through a process that mimics the human brain.",
  "Deep Learning": "Part of a broader family of machine learning methods based on artificial neural networks with representation learning.",
  "Gradient Descent": "A first-order iterative optimization algorithm for finding a local minimum of a differentiable function.",
  "Overfitting": "The production of an analysis that corresponds too closely to a particular set of data.",
  "Underfitting": "When a statistical model cannot adequately capture the underlying structure of the data.",
  "Epoch": "One complete presentation of the data set to be learned to a learning machine.",
  "Batch Size": "The number of training examples utilized in one iteration.",
  "Learning Rate": "A tuning parameter in an optimization algorithm that determines the step size at each iteration while moving toward a minimum.",

  "Agile": "A set of frameworks and practices based on the values and principles expressed in the Manifesto for Agile Software Development.",
  "Scrum": "An agile framework for developing, delivering, and sustaining complex products.",
  "Waterfall": "A breakdown of project activities into linear sequential phases, where each phase depends on the deliverables of the previous one.",
  "Git": "A distributed version-control system for tracking changes in source code during software development.",
  "CI/CD": "Continuous Integration and Continuous Deployment, practices designed to automate the integration and delivery of code changes.",
  "TDD": "Test-driven development is a software development process relying on software requirements being converted to test cases.",
  "Design Patterns": "A general, reusable solution to a commonly occurring problem within a given context in software design.",
  "MVC": "Model-View-Controller is a software design pattern commonly used for developing user interfaces.",
  "Singleton": "A software design pattern that restricts the instantiation of a class to one single instance.",
  "Observer": "A software design pattern in which an object, named the subject, maintains a list of its dependents, called observers.",

  "Calculus": "The mathematical study of continuous change.",
  "Linear Algebra": "The branch of mathematics concerning linear equations, linear maps and their representations in vector spaces.",
  "Probability": "The branch of mathematics concerning numerical descriptions of how likely an event is to occur.",
  "Statistics": "The discipline that concerns the collection, organization, analysis, interpretation, and presentation of data.",
  "Matrix": "A rectangular array or table of numbers, symbols, or expressions, arranged in rows and columns.",
  "Vector": "A quantity that has both magnitude and direction.",
  "Derivative": "The rate of change of a function with respect to a variable.",
  "Integral": "Assigns numbers to functions in a way that can describe displacement, area, volume, and other concepts that arise by combining infinitesimal data.",
  "Eigenvalue": "A scalar associated with a given linear transformation of a vector space.",
  "Eigenvector": "A non-zero vector that changes at most by a scalar factor when that linear transformation is applied to it.",

  "Newton First Law": "An object will remain at rest or in uniform motion in a straight line unless acted upon by an external force.",
  "Newton Second Law": "The acceleration of an object is dependent upon two variables - the net force acting upon the object and the mass of the object.",
  "Newton Third Law": "For every action, there is an equal and opposite reaction.",
  "Gravity": "A fundamental interaction which causes mutual attraction between all things with mass or energy.",
  "Velocity": "The directional speed of an object in motion as an indicator of its rate of change in position as observed from a particular frame of reference.",
  "Acceleration": "The rate of change of the velocity of an object with respect to time.",
  "Force": "Any interaction that, when unopposed, will change the motion of an object.",
  "Energy": "The quantitative property that must be transferred to a body or physical system to perform work on the body, or to heat it.",
  "Work": "The energy transferred to or from an object via the application of force along a displacement.",
  "Power": "The amount of energy transferred or converted per unit time.",

  "Atom": "The smallest unit of ordinary matter that forms a chemical element.",
  "Molecule": "An electrically neutral group of two or more atoms held together by chemical bonds.",
  "Proton": "A subatomic particle with a positive electric charge.",
  "Neutron": "A subatomic particle with no net electric charge.",
  "Electron": "A subatomic particle with a negative elementary electric charge.",
  "Periodic Table": "A tabular display of the chemical elements.",
  "Covalent Bond": "A chemical bond that involves the sharing of electron pairs between atoms.",
  "Ionic Bond": "A type of chemical bonding that involves the electrostatic attraction between oppositely charged ions.",
  "Isotope": "Variants of a particular chemical element which differ in neutron number.",
  "pH": "A scale used to specify the acidity or basicity of an aqueous solution.",

  "Cell": "The basic structural, functional, and biological unit of all known organisms.",
  "DNA": "A molecule composed of two polynucleotide chains that coil around each other to form a double helix.",
  "RNA": "A polymeric molecule essential in various biological roles in coding, decoding, regulation and expression of genes.",
  "Protein": "Large biomolecules and macromolecules that comprise one or more long chains of amino acid residues.",
  "Enzyme": "Proteins that act as biological catalysts.",
  "Mitochondria": "Double-membrane-bound organelles found in most eukaryotic organisms. Often called the powerhouse of the cell.",
  "Nucleus": "A membrane-bound organelle found in eukaryotic cells.",
  "Photosynthesis": "A process used by plants and other organisms to convert light energy into chemical energy.",
  "Respiration": "A metabolic reaction that takes place in the cells of organisms to convert biochemical energy from nutrients into ATP.",
  "Mitosis": "A part of the cell cycle in which replicated chromosomes are separated into two new nuclei.",

  "World War I": "A global war originating in Europe that lasted from 28 July 1914 to 11 November 1918.",
  "World War II": "A global war that lasted from 1939 to 1945.",
  "Cold War": "A period of geopolitical tension between the Soviet Union and the United States and their respective allies.",
  "Renaissance": "A period in European history marking the transition from the Middle Ages to modernity and covering the 15th and 16th centuries.",
  "Industrial Revolution": "The transition to new manufacturing processes in Europe and the United States, in the period from about 1760 to sometime between 1820 and 1840.",
  "French Revolution": "A period of far-reaching social and political upheaval in France that began in 1789 and ended in 1799.",
  "American Revolution": "An ideological and political revolution which occurred in colonial North America between 1765 and 1783.",
  "Roman Empire": "The post-Republican period of ancient Rome, consisting of large territorial holdings around the Mediterranean Sea in Europe, North Africa and Western Asia.",
  "Ancient Egypt": "A civilization of ancient North Africa, concentrated along the lower reaches of the Nile River.",
  "Feudalism": "A combination of legal, economic, military, and cultural customs that flourished in Medieval Europe between the 9th and 15th centuries."
};

const topics = [
  { topic: 'Data Structures', terms: ['Array', 'Linked List', 'Stack', 'Queue', 'Tree', 'Graph', 'Hash Table', 'Heap', 'Trie', 'B-Tree'] },
  { topic: 'Algorithms', terms: ['Binary Search', 'Merge Sort', 'Quick Sort', 'Bubble Sort', 'Dijkstra', 'DFS', 'BFS', 'Dynamic Programming', 'Greedy', 'Backtracking'] },
  { topic: 'Web Development', terms: ['HTML', 'CSS', 'JavaScript', 'React', 'DOM', 'REST API', 'GraphQL', 'JWT', 'CORS', 'WebSockets'] },
  { topic: 'Databases', terms: ['SQL', 'NoSQL', 'Normalization', 'ACID', 'Index', 'Foreign Key', 'Primary Key', 'Join', 'Transaction', 'Sharding'] },
  { topic: 'Networking', terms: ['TCP', 'UDP', 'HTTP', 'HTTPS', 'DNS', 'IP Address', 'MAC Address', 'Router', 'Switch', 'Firewall'] },
  { topic: 'Operating Systems', terms: ['Process', 'Thread', 'Deadlock', 'Mutex', 'Semaphore', 'Virtual Memory', 'Paging', 'Scheduling', 'Kernel', 'Shell'] },
  { topic: 'Cybersecurity', terms: ['Phishing', 'Malware', 'Encryption', 'Decryption', 'Symmetric Key', 'Asymmetric Key', 'Hash Function', 'Salting', 'VPN', 'DDoS'] },
  { topic: 'Cloud Computing', terms: ['IaaS', 'PaaS', 'SaaS', 'AWS', 'Azure', 'Docker', 'Kubernetes', 'Serverless', 'Microservices', 'Load Balancer'] },
  { topic: 'Machine Learning', terms: ['Supervised Learning', 'Unsupervised Learning', 'Neural Network', 'Deep Learning', 'Gradient Descent', 'Overfitting', 'Underfitting', 'Epoch', 'Batch Size', 'Learning Rate'] },
  { topic: 'Software Engineering', terms: ['Agile', 'Scrum', 'Waterfall', 'Git', 'CI/CD', 'TDD', 'Design Patterns', 'MVC', 'Singleton', 'Observer'] },
  { topic: 'Mathematics', terms: ['Calculus', 'Linear Algebra', 'Probability', 'Statistics', 'Matrix', 'Vector', 'Derivative', 'Integral', 'Eigenvalue', 'Eigenvector'] },
  { topic: 'Physics', terms: ['Newton First Law', 'Newton Second Law', 'Newton Third Law', 'Gravity', 'Velocity', 'Acceleration', 'Force', 'Energy', 'Work', 'Power'] },
  { topic: 'Chemistry', terms: ['Atom', 'Molecule', 'Proton', 'Neutron', 'Electron', 'Periodic Table', 'Covalent Bond', 'Ionic Bond', 'Isotope', 'pH'] },
  { topic: 'Biology', terms: ['Cell', 'DNA', 'RNA', 'Protein', 'Enzyme', 'Mitochondria', 'Nucleus', 'Photosynthesis', 'Respiration', 'Mitosis'] },
  { topic: 'History', terms: ['World War I', 'World War II', 'Cold War', 'Renaissance', 'Industrial Revolution', 'French Revolution', 'American Revolution', 'Roman Empire', 'Ancient Egypt', 'Feudalism'] }
];

const cards = [];
let idCounter = 1;

topics.forEach(t => {
  t.terms.forEach(term => {
    cards.push({
      id: `mock-fc-${idCounter++}`,
      front: `What is the definition of ${term} in ${t.topic}?`,
      back: definitions[term] || `A fundamental concept in ${t.topic}.`,
      deck_id: 'default',
      created_at: new Date().toISOString()
    });
  });
});

fs.writeFileSync('./frontend/src/data/flashcards150.json', JSON.stringify(cards, null, 2));
console.log(`Generated ${cards.length} flashcards with real definitions.`);
